apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: java-demoapp
  namespace: demoapp
spec:
  rules:
  - host: java.demoapp.example.com
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: http
            port:
              name: http